### NumPy

In [1]:
import numpy as np

### 1D array

In [2]:
a=np.array([10,20,30,50])

### Attributes of arrays

##### dtype

In [3]:
a.dtype

dtype('int32')

##### ndim

In [4]:
a.ndim

1

##### size

In [5]:
a.size

4

##### shape

In [6]:
a.shape

(4,)

In [7]:
a[0]

10

In [8]:
a[2]

30

### Multi dimensional array

In [9]:
a_2d = np.array([[10,20,30],[15,25,35]])

In [10]:
a_2d

array([[10, 20, 30],
       [15, 25, 35]])

In [11]:
a_2d.dtype

dtype('int32')

In [12]:
a_2d.shape

(2, 3)

In [13]:
a_2d.ndim

2

In [14]:
a_2d.size

6

In [15]:
a_2d[0]

array([10, 20, 30])

### Another type of multi dimensional arrays

In [16]:
another_type_array = np.array([[[1,2,3],[3,4,5],[6,7,8]]])

In [17]:
another_type_array

array([[[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]]])

In [18]:
another_type_array.shape

(1, 3, 3)

In [19]:
another_type_array.ndim

3

#### First element in first array

In [20]:
a_2d[0][0]

10

#### Second element in second array

In [21]:
a_2d[1][1]

25

#### Lets change its data type into float

In [22]:
a_2d = np.array([[10,20,30],[15,25,35]],dtype = float)

In [23]:
a_2d

array([[10., 20., 30.],
       [15., 25., 35.]])

### Lets create a bigger array

In [24]:
a_bigger = np.array([
[
[10,20,30,40],[2,4,6,8],[1,2,3,4]
],
[
[9,9,4,2],[1,1,2,3],[0,2,0,1]
],
[
[12,33,21,1],[22,1,22,2],[0,2,3,7]
]
],dtype = float)

In [25]:
a_bigger

array([[[10., 20., 30., 40.],
        [ 2.,  4.,  6.,  8.],
        [ 1.,  2.,  3.,  4.]],

       [[ 9.,  9.,  4.,  2.],
        [ 1.,  1.,  2.,  3.],
        [ 0.,  2.,  0.,  1.]],

       [[12., 33., 21.,  1.],
        [22.,  1., 22.,  2.],
        [ 0.,  2.,  3.,  7.]]])

In [26]:
a_bigger.shape

(3, 3, 4)

In [27]:
a_bigger.ndim

3

In [28]:
a_bigger.size

36

In [29]:
a_bigger[2][2][3]

7.0

In [30]:
a_bigger[2][2]

array([0., 2., 3., 7.])

### Filling arrays

##### np.full

##### By using the full function for example, we fill an array of a certain shape with the same number. In this case we create a 3x5x4 matrix, which is filled with sevens. 


In [31]:
a_full = np.full((3,5,4),7)

In [32]:
a_full

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [33]:
a_full.ndim

3

### ZEROS AND ONES

#### For the cases that we want arrays full of zeros or ones, we even have specific functions.

In [34]:
a_zeros = np.zeros((3,3))
a_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
b_zeros = np.ones((2,3,4))
b_zeros

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [36]:
b_zeros.ndim

3

### EMPTY AND RANDOM

#### Other options would be to create an empty array or one that is filled with random numbers. For this, we use the respective functions once again. 


In [37]:
e = np.empty((4,4))

In [38]:
np.set_printoptions(suppress=True)

In [39]:
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
b_random = np.random.random((2,2))

In [41]:
b_random

array([[0.79950669, 0.99975211],
       [0.41211941, 0.32732342]])

In [42]:
b_random.ndim

2

In [43]:
b_random.size

4

### RANGES

#### Instead of just filling arrays with the same values, we can fill create sequences of values by specifying the boundaries. For this, we can use two different functions, namely arange and linspace. 


#### Arange
###### Arguements are : start-stop-step

In [44]:
e_arange = np.arange(10,50,5)
e_arange

array([10, 15, 20, 25, 30, 35, 40, 45])

### Linspace

#### By using linspace we also create a list from a minimum value to a maximum value. But instead of specifying the step-size, we specify the amount of values that we want to have in our list. They will all be spread evenly and have the same distance to their neighbors. 


#### start-stop-number of values

In [45]:
b_linspace = np.linspace(0,50,3)
b_linspace

array([ 0., 25., 50.])

In [46]:
b_linspace.ndim

1

In [47]:
b_linspace.size

3

In [48]:
b_linspace1 = np.linspace(0,50,30)
b_linspace1

array([ 0.        ,  1.72413793,  3.44827586,  5.17241379,  6.89655172,
        8.62068966, 10.34482759, 12.06896552, 13.79310345, 15.51724138,
       17.24137931, 18.96551724, 20.68965517, 22.4137931 , 24.13793103,
       25.86206897, 27.5862069 , 29.31034483, 31.03448276, 32.75862069,
       34.48275862, 36.20689655, 37.93103448, 39.65517241, 41.37931034,
       43.10344828, 44.82758621, 46.55172414, 48.27586207, 50.        ])

In [49]:
b_linspace1.size

30

In [50]:
b_linspace2 = np.linspace(0,50,25,dtype=int)
b_linspace2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 50])

### Math functions

#### np.exp(a)
##### Takes e to the power of each value

In [51]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 5.18470553e+21])

#### np.sin(a)
##### Returns the sin of each vale

In [52]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162, -0.26237485])

#### np.cos(a)
##### Returns the cosine of each value

In [53]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145,  0.96496603])

#### np.tan(a)
##### Returns the tangent of each values

In [54]:
np.tan(a)

array([ 0.64836083,  2.23716094, -6.4053312 , -0.27190061])

#### np.log(a)
##### Returns the logarithm of each value

In [55]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.91202301])

#### np.sqrt(a)
##### Returns the square root of each value

In [56]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 7.07106781])

### AGGREGATE FUNCTIONS

#### a.sum()
##### Returns the sum of all values in the array

In [57]:
a.sum()

110

#### a.min()
##### Returns the lowest value of the array

In [58]:
a.min()

10

#### a.max()
##### Returns the highest value of the array

In [59]:
a.max()

50

#### a.mean()
##### Return the arithmetic mean of all values in the array

In [60]:
a.mean()

27.5

#### np.median(a)
##### Returns the median of all values in the array

In [61]:
np.median(a)

25.0

#### np.std(a)
##### Returns the standard deviation of the values in the array

In [62]:
np.std(a)

14.79019945774904

#### Create some arrays and apply all the functions

###### Eg:

In [63]:
np.median(b_linspace2)

25.0

In [64]:
np.sum(b_linspace2)

614

In [65]:
np.sqrt(b_linspace2)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595, 4.69041576, 5.        , 5.19615242, 5.38516481,
       5.56776436, 5.74456265, 5.91607978, 6.08276253, 6.244998  ,
       6.40312424, 6.55743852, 6.70820393, 6.8556546 , 7.07106781])

In [66]:
np.std(b_linspace2)

14.924020905908701

In [67]:
np.cos(b_linspace2)

array([ 1.        , -0.41614684, -0.65364362,  0.96017029, -0.14550003,
       -0.83907153,  0.84385396,  0.13673722, -0.95765948,  0.66031671,
        0.40808206, -0.99996083,  0.99120281, -0.29213881, -0.74805753,
        0.91474236, -0.01327675, -0.90369221,  0.76541405,  0.26664293,
       -0.98733928,  0.5551133 ,  0.52532199, -0.99233547,  0.96496603])